-- =====================================================================
--  Resolver un anticipo que se quedó "disponible" en una OC que ya no se
--  va a completar (el proveedor no entrega el resto). Hasta ahora ese
--  saldo se quedaba atado para siempre a esa OC en v_anticipos_oc, sin
--  ninguna pantalla para decidir qué hacer con él.
--  Fecha: 2026-10-29 (secuencia)  ·  Proyecto: Hares de México (Supabase)
--
--  NO lo ejecuta la app. Pegar y correr A MANO en Supabase -> SQL Editor.
--  Requiere sql/2026-10-27_anticipo_proveedores.sql (ya corrida).
--
--  3 escenarios reales, a petición del usuario (cada uno con su propio
--  tratamiento contable — no es solo "que cuadre", es NIF: dinero
--  recuperable sigue siendo activo, dinero perdido es un gasto):
--   1. 'reasignado' — el proveedor deja aplicar el saldo a la SIGUIENTE
--      compra que le hagas (incluso a otra OC). Sin póliza: el dinero
--      nunca salió de 109.01, solo se reetiqueta a qué OC pertenece el
--      derecho a usarlo.
--   2. 'reembolsado' — el proveedor te regresa el efectivo. Póliza
--      Ingreso: Cargo banco / Abono 109.01 (ya no es "a favor", ya es
--      caja otra vez).
--   3. 'baja' — el proveedor no va a devolver nada y no habrá otra
--      compra. Póliza Diario: Cargo a una cuenta de gasto (la que
--      corresponda, elegida a mano) / Abono 109.01 — es una pérdida real,
--      NIF no permite dejarla como si siguiera siendo un activo.
--
--  Idempotente (create table if not exists, create or replace function/view).
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Tabla: cada fila es una resolución (total o parcial) del saldo
--    disponible de una OC.
-- ---------------------------------------------------------------------
create table if not exists public.anticipo_oc_resoluciones (
    id              bigint generated by default as identity primary key,
    orden_compra_id bigint not null references public.ordenes_compra (id),
    tipo            text not null check (tipo in ('reasignado', 'reembolsado', 'baja')),
    monto           numeric(14,2) not null check (monto > 0),
    oc_destino_id   bigint references public.ordenes_compra (id),   -- solo 'reasignado'
    poliza_id       bigint references public.polizas (id),          -- 'reembolsado' / 'baja'
    fecha           date not null default current_date,
    notas           text,
    creado_por      uuid references auth.users (id),
    creado_at       timestamptz not null default now(),
    constraint anticipo_oc_resoluciones_chk check (
        (tipo = 'reasignado'   and oc_destino_id is not null and poliza_id is null) or
        (tipo = 'reembolsado'  and oc_destino_id is null and poliza_id is not null) or
        (tipo = 'baja'         and oc_destino_id is null and poliza_id is not null)
    )
);
create index if not exists anticipo_oc_resoluciones_oc_idx on public.anticipo_oc_resoluciones (orden_compra_id);
create index if not exists anticipo_oc_resoluciones_destino_idx on public.anticipo_oc_resoluciones (oc_destino_id);

alter table public.anticipo_oc_resoluciones enable row level security;
drop policy if exists anticipo_oc_resoluciones_select on public.anticipo_oc_resoluciones;
create policy anticipo_oc_resoluciones_select on public.anticipo_oc_resoluciones for select to authenticated using (true);
grant select on public.anticipo_oc_resoluciones to authenticated;

-- ---------------------------------------------------------------------
-- 2. _saldo_anticipo_oc() — ahora también descuenta lo resuelto (salida
--    de esta OC) y suma lo reasignado ENTRANTE desde otra OC.
-- ---------------------------------------------------------------------
create or replace function public._saldo_anticipo_oc(p_oc_id bigint)
returns numeric
language sql
stable
as $$
    select round(
        coalesce((
            select sum(a.monto) from public.pagos_proveedor_aplicaciones a
            join public.pagos_proveedor pp on pp.id = a.pago_id
           where a.tipo = 'anticipo_oc' and a.orden_compra_id = p_oc_id and pp.estatus = 'registrado'
        ), 0)
        -
        coalesce((
            select sum(a2.monto) from public.pagos_proveedor_aplicaciones a2
            join public.pagos_proveedor_aplicaciones a1 on a1.id = a2.aplicacion_origen_id
           where a2.tipo = 'anticipo_aplicado' and a1.tipo = 'anticipo_oc' and a1.orden_compra_id = p_oc_id
        ), 0)
        -
        coalesce((
            select sum(r.monto) from public.anticipo_oc_resoluciones r
           where r.orden_compra_id = p_oc_id
        ), 0)
        +
        coalesce((
            select sum(r.monto) from public.anticipo_oc_resoluciones r
           where r.oc_destino_id = p_oc_id and r.tipo = 'reasignado'
        ), 0)
    , 2);
$$;

-- ---------------------------------------------------------------------
-- 3. resolver_anticipo_oc(p_oc_id, p_datos) -> jsonb
-- ---------------------------------------------------------------------
create or replace function public.resolver_anticipo_oc(p_oc_id bigint, p_datos jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_oc        public.ordenes_compra%rowtype;
    v_tipo      text := nullif(trim(p_datos->>'tipo'), '');
    v_monto     numeric(14,2) := round(coalesce((p_datos->>'monto')::numeric, 0), 2);
    v_fecha     date := coalesce((p_datos->>'fecha')::date, current_date);
    v_notas     text := nullif(trim(p_datos->>'notas'), '');
    v_disp      numeric(14,2);
    v_res_id    bigint;
    v_poliza_id bigint;

    v_oc_dest   public.ordenes_compra%rowtype;

    v_cta_banco bigint := (p_datos->>'cuenta_banco_id')::bigint;
    v_cuenta    public.cuentas_contables%rowtype;

    v_cta_gasto bigint := (p_datos->>'cuenta_gasto_id')::bigint;
begin
    if v_tipo not in ('reasignado', 'reembolsado', 'baja') then
        raise exception 'Tipo de resolución inválido: %. Debe ser reasignado, reembolsado o baja.', v_tipo;
    end if;
    if v_monto <= 0 then raise exception 'El monto a resolver debe ser mayor a cero.'; end if;

    select * into v_oc from public.ordenes_compra where id = p_oc_id;
    if not found then raise exception 'La orden de compra no existe.'; end if;

    v_disp := coalesce(public._saldo_anticipo_oc(p_oc_id), 0);
    if v_monto > v_disp + 0.01 then
        raise exception 'El monto (%) supera el anticipo disponible de esta OC (%). Revisa el Auxiliar de Anticipos.',
            to_char(v_monto, 'FM999999990.00'), to_char(v_disp, 'FM999999990.00');
    end if;

    if v_tipo = 'reasignado' then
        select * into v_oc_dest from public.ordenes_compra where id = (p_datos->>'oc_destino_id')::bigint;
        if not found then raise exception 'La orden de compra destino no existe.'; end if;
        if v_oc_dest.id = v_oc.id then raise exception 'La OC destino no puede ser la misma OC.'; end if;
        if v_oc_dest.proveedor_id is distinct from v_oc.proveedor_id then
            raise exception 'La OC destino es de otro proveedor — un anticipo solo se puede reasignar dentro del mismo proveedor.';
        end if;
        if v_oc_dest.estatus not in ('abierta', 'recibida_parcial') then
            raise exception 'La OC destino debe estar abierta o parcialmente recibida (estatus actual: %).', v_oc_dest.estatus;
        end if;

        insert into public.anticipo_oc_resoluciones (orden_compra_id, tipo, monto, oc_destino_id, fecha, notas)
        values (p_oc_id, 'reasignado', v_monto, v_oc_dest.id, v_fecha, v_notas)
        returning id into v_res_id;

    elsif v_tipo = 'reembolsado' then
        select * into v_cuenta from public.cuentas_contables where id = v_cta_banco;
        if not found then raise exception 'Selecciona la cuenta de banco / caja donde entra el reembolso.'; end if;
        if not v_cuenta.afectable or not v_cuenta.activa then
            raise exception 'La cuenta % no acepta movimientos o está inactiva.', v_cuenta.codigo;
        end if;

        v_poliza_id := (public.registrar_poliza(jsonb_build_object(
            'fecha', v_fecha, 'tipo', 'Ingreso',
            'concepto', 'Reembolso de anticipo - OC ' || coalesce(v_oc.folio, '#' || v_oc.id) || coalesce(' - ' || v_notas, ''),
            'origen', 'anticipo_reembolso', 'origen_tabla', 'ordenes_compra', 'origen_id', p_oc_id,
            'movimientos', jsonb_build_array(
                jsonb_build_object('cuenta_id', v_cta_banco, 'cargo', v_monto,
                    'concepto', 'Reembolso de anticipo OC ' || coalesce(v_oc.folio, '#' || v_oc.id)),
                jsonb_build_object('cuenta_id', public._cuenta_id('109.01'), 'abono', v_monto,
                    'concepto', 'Anticipo reembolsado', 'proveedor_id', v_oc.proveedor_id)
            )
        ))->>'poliza_id')::bigint;

        insert into public.anticipo_oc_resoluciones (orden_compra_id, tipo, monto, poliza_id, fecha, notas)
        values (p_oc_id, 'reembolsado', v_monto, v_poliza_id, v_fecha, v_notas)
        returning id into v_res_id;

    else -- 'baja'
        select * into v_cuenta from public.cuentas_contables where id = v_cta_gasto;
        if not found then raise exception 'Selecciona la cuenta de gasto / pérdida contra la que se da de baja.'; end if;
        if not v_cuenta.afectable or not v_cuenta.activa then
            raise exception 'La cuenta % no acepta movimientos o está inactiva.', v_cuenta.codigo;
        end if;

        v_poliza_id := (public.registrar_poliza(jsonb_build_object(
            'fecha', v_fecha, 'tipo', 'Diario',
            'concepto', 'Baja de anticipo no recuperable - OC ' || coalesce(v_oc.folio, '#' || v_oc.id) || coalesce(' - ' || v_notas, ''),
            'origen', 'anticipo_baja', 'origen_tabla', 'ordenes_compra', 'origen_id', p_oc_id,
            'movimientos', jsonb_build_array(
                jsonb_build_object('cuenta_id', v_cta_gasto, 'cargo', v_monto,
                    'concepto', 'Anticipo no recuperable - OC ' || coalesce(v_oc.folio, '#' || v_oc.id), 'proveedor_id', v_oc.proveedor_id),
                jsonb_build_object('cuenta_id', public._cuenta_id('109.01'), 'abono', v_monto,
                    'concepto', 'Baja de anticipo', 'proveedor_id', v_oc.proveedor_id)
            )
        ))->>'poliza_id')::bigint;

        insert into public.anticipo_oc_resoluciones (orden_compra_id, tipo, monto, poliza_id, fecha, notas)
        values (p_oc_id, 'baja', v_monto, v_poliza_id, v_fecha, v_notas)
        returning id into v_res_id;
    end if;

    return jsonb_build_object('resolucion_id', v_res_id, 'poliza_id', v_poliza_id, 'tipo', v_tipo, 'monto', v_monto);
end $$;

revoke all     on function public.resolver_anticipo_oc(bigint, jsonb) from public, anon;
grant  execute on function public.resolver_anticipo_oc(bigint, jsonb) to authenticated;

-- ---------------------------------------------------------------------
-- 4. v_anticipos_oc — "disponible" ahora también refleja lo resuelto, y
--    la OC ya aparece aunque NUNCA haya tenido su propio anticipo pagado
--    directo, si lo que tiene es saldo REASIGNADO desde otra OC (antes el
--    join arrancaba desde pagos_proveedor_aplicaciones y esa OC destino
--    simplemente no salía en la vista). El cálculo de pagado/aplicado
--    (columnas informativas) es copia exacta de la vista vigente de
--    sql/2026-10-27_anticipo_proveedores.sql — solo se cambió a LEFT JOIN
--    para no perder las OCs sin anticipo propio, y se agregó el ajuste de
--    "disponible" por lo resuelto/reasignado.
-- ---------------------------------------------------------------------
create or replace view public.v_anticipos_oc as
    with ocs_relevantes as (
        select orden_compra_id as id from public.pagos_proveedor_aplicaciones where tipo = 'anticipo_oc'
        union
        select oc_destino_id as id from public.anticipo_oc_resoluciones where tipo = 'reasignado' and oc_destino_id is not null
    )
    select oc.id as orden_compra_id, oc.folio, oc.proveedor_id, pv.nombre as proveedor_nombre,
           coalesce(sum(a.monto) filter (where pp.estatus = 'registrado'), 0) as pagado,
           coalesce(sum(a2.monto), 0) as aplicado,
           round(
               coalesce(sum(a.monto) filter (where pp.estatus = 'registrado'), 0)
               - coalesce(sum(a2.monto), 0)
               - coalesce((select sum(r.monto) from public.anticipo_oc_resoluciones r where r.orden_compra_id = oc.id), 0)
               + coalesce((select sum(r.monto) from public.anticipo_oc_resoluciones r where r.oc_destino_id = oc.id and r.tipo = 'reasignado'), 0)
           , 2) as disponible
      from ocs_relevantes orv
      join public.ordenes_compra oc on oc.id = orv.id
      left join public.pagos_proveedor_aplicaciones a on a.orden_compra_id = oc.id and a.tipo = 'anticipo_oc'
      left join public.pagos_proveedor pp on pp.id = a.pago_id
      left join public.proveedores pv on pv.id = oc.proveedor_id
      left join public.pagos_proveedor_aplicaciones a2 on a2.aplicacion_origen_id = a.id and a2.tipo = 'anticipo_aplicado'
     group by oc.id, oc.folio, oc.proveedor_id, pv.nombre;

grant select on public.v_anticipos_oc to authenticated;

commit;
