-- =====================================================================
--  Tareas / sugerencias del sistema — bandeja persistente con estatus
--  Fecha: 2026-09-06  ·  Proyecto: Hares de México (Supabase)
--
--  NO lo ejecuta la app. Pegar y correr A MANO en Supabase -> SQL Editor.
--
--  Crea public.tareas: una sola tabla para TODO tipo de pendiente que el
--  sistema genera solo (columna 'tipo'). El primer tipo es
--  'inventario_bajo_minimo': cuando productos.stock_actual <= stock_minimo
--  se crea una tarea; cuando la existencia se recupera, se archiva sola.
--
--  Flujo de estatus:
--    pendiente  -> aparece en la bandeja (js/tareas.js)
--    atendida   -> el usuario ya actuó (creó la orden de compra, compró...)
--    pospuesta  -> el usuario la marcó "no aceptada"; se oculta hasta
--                  posponer_hasta y, si sigue aplicando, el job diario la
--                  regresa a 'pendiente'
--    archivada  -> la condición dejó de aplicar (stock arriba del mínimo,
--                  producto inactivo). Terminal; queda como historial.
--
--  Piezas:
--    · tabla public.tareas + índice único parcial (una tarea viva por
--      producto y tipo)
--    · public.tareas_sync_inventario(p_producto_id)  crea / archiva /
--      reactiva (una fila o todas si NULL)
--    · trigger en productos (stock_actual / stock_minimo / activo) que
--      llama a tareas_sync_inventario en tiempo real
--    · public.tarea_resolver(id, accion, nota, dias)  para los botones
--    · job de pg_cron diario 07:15 CDMX (reconciliación + reactivación)
--    · backfill al final
--
--  Idempotente.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Tabla
-- ---------------------------------------------------------------------
create table if not exists public.tareas (
    id              bigint generated by default as identity primary key,
    tipo            text        not null,
    estatus         text        not null default 'pendiente'
                    check (estatus in ('pendiente','atendida','pospuesta','archivada')),
    prioridad       smallint    not null default 2,   -- 1 alta · 2 normal · 3 baja
    titulo          text        not null,
    detalle         text,
    entidad_tipo    text,                              -- 'producto', ...
    entidad_id      bigint,
    datos           jsonb       not null default '{}'::jsonb,
    origen          text        not null default 'sistema'
                    check (origen in ('sistema','manual')),
    accion_sugerida text,                              -- p.ej. 'crear_orden_compra'
    creada_en       timestamptz not null default now(),
    actualizada_en  timestamptz not null default now(),
    posponer_hasta  timestamptz,
    resuelta_en     timestamptz,
    resuelta_por    uuid,
    nota_resolucion text
);

-- columnas nuevas si la tabla ya existía de una corrida previa
alter table public.tareas add column if not exists prioridad       smallint    not null default 2;
alter table public.tareas add column if not exists detalle         text;
alter table public.tareas add column if not exists entidad_tipo    text;
alter table public.tareas add column if not exists entidad_id      bigint;
alter table public.tareas add column if not exists datos           jsonb       not null default '{}'::jsonb;
alter table public.tareas add column if not exists origen          text        not null default 'sistema';
alter table public.tareas add column if not exists accion_sugerida text;
alter table public.tareas add column if not exists actualizada_en  timestamptz not null default now();
alter table public.tareas add column if not exists posponer_hasta  timestamptz;
alter table public.tareas add column if not exists resuelta_en     timestamptz;
alter table public.tareas add column if not exists resuelta_por    uuid;
alter table public.tareas add column if not exists nota_resolucion text;

-- una sola tarea "viva" (no archivada) por tipo + entidad
create unique index if not exists tareas_entidad_viva_uq
    on public.tareas (tipo, entidad_tipo, entidad_id)
    where estatus <> 'archivada';

create index if not exists tareas_estatus_idx   on public.tareas (estatus);
create index if not exists tareas_tipo_idx      on public.tareas (tipo);

alter table public.tareas enable row level security;
drop policy if exists admin_all on public.tareas;
create policy admin_all on public.tareas for all to authenticated using (true) with check (true);
grant all on public.tareas to authenticated;

comment on table public.tareas is
  'Bandeja de pendientes generados por el sistema (y manuales). Un tipo por columna "tipo".';


-- ---------------------------------------------------------------------
-- 2. Sincronizador de tareas de inventario
--    p_producto_id NULL = recorre todos los productos.
--    Devuelve cuántas filas de productos tocó (creó/actualizó/archivó).
-- ---------------------------------------------------------------------
create or replace function public.tareas_sync_inventario(p_producto_id bigint default null)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    r        record;
    v_bajo   boolean;
    v_falt   numeric;
    v_sug    numeric;
    v_tot    integer := 0;
begin
    for r in
        select p.id, p.nombre, p.sku, coalesce(p.activo, true) as activo,
               coalesce(p.stock_actual, 0)  as stock_actual,
               coalesce(p.stock_minimo, 0)  as stock_minimo,
               p.cantidad_minima_compra, p.tiempo_entrega_dias, p.proveedor_id
        from public.productos p
        where p_producto_id is null or p.id = p_producto_id
    loop
        v_bajo := r.activo and r.stock_minimo > 0 and r.stock_actual <= r.stock_minimo;

        if v_bajo then
            v_falt := r.stock_minimo - r.stock_actual;
            v_sug  := greatest(coalesce(r.cantidad_minima_compra, 0), v_falt);

            insert into public.tareas
                (tipo, estatus, prioridad, titulo, detalle,
                 entidad_tipo, entidad_id, datos, origen, accion_sugerida)
            values
                ('inventario_bajo_minimo',
                 'pendiente',
                 case when r.stock_actual <= 0 then 1 else 2 end,
                 'Comprar: ' || r.nombre,
                 'Existencia ' || trim(to_char(r.stock_actual, 'FM999999990.####'))
                    || ' · mínimo ' || trim(to_char(r.stock_minimo, 'FM999999990.####'))
                    || ' · sugerido pedir ' || trim(to_char(v_sug, 'FM999999990.####')),
                 'producto', r.id,
                 jsonb_build_object(
                    'sku', r.sku,
                    'stock_actual', r.stock_actual,
                    'stock_minimo', r.stock_minimo,
                    'faltante', v_falt,
                    'sugerido_pedir', v_sug,
                    'proveedor_id', r.proveedor_id,
                    'tiempo_entrega_dias', r.tiempo_entrega_dias),
                 'sistema', 'crear_orden_compra')
            on conflict (tipo, entidad_tipo, entidad_id) where estatus <> 'archivada'
            do update set
                prioridad      = excluded.prioridad,
                titulo         = excluded.titulo,
                detalle        = excluded.detalle,
                datos          = excluded.datos,
                actualizada_en = now(),
                -- si estaba pospuesta y ya venció el aplazamiento, reactivar
                estatus        = case
                    when tareas.estatus = 'pospuesta'
                     and tareas.posponer_hasta is not null
                     and tareas.posponer_hasta <= now()
                    then 'pendiente' else tareas.estatus end,
                posponer_hasta = case
                    when tareas.estatus = 'pospuesta'
                     and tareas.posponer_hasta is not null
                     and tareas.posponer_hasta <= now()
                    then null else tareas.posponer_hasta end;

            v_tot := v_tot + 1;

        else
            -- ya no aplica: archivar cualquier tarea viva de este producto
            update public.tareas
            set estatus         = 'archivada',
                resuelta_en     = now(),
                actualizada_en  = now(),
                nota_resolucion = coalesce(nota_resolucion,
                    'Archivada automáticamente: la existencia dejó de estar bajo el mínimo.')
            where tipo = 'inventario_bajo_minimo'
              and entidad_tipo = 'producto'
              and entidad_id = r.id
              and estatus <> 'archivada';
            if found then v_tot := v_tot + 1; end if;
        end if;
    end loop;

    return v_tot;
end $$;

grant execute on function public.tareas_sync_inventario(bigint) to authenticated;


-- ---------------------------------------------------------------------
-- 3. Trigger en productos — dispara el sync en tiempo real
--    (cubre TODOS los caminos: la RPC FIFO y las salidas que ajustan
--     productos.stock_actual directamente terminan en un UPDATE aquí)
-- ---------------------------------------------------------------------
create or replace function public.fn_productos_tareas_inventario()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    perform public.tareas_sync_inventario(new.id);
    return null;   -- AFTER trigger
end $$;

drop trigger if exists trg_productos_tareas_inventario on public.productos;
create trigger trg_productos_tareas_inventario
    after insert or update of stock_actual, stock_minimo, activo on public.productos
    for each row execute function public.fn_productos_tareas_inventario();


-- ---------------------------------------------------------------------
-- 4. Resolver una tarea desde los botones de la bandeja
--    acciones: 'atender' | 'posponer' | 'archivar' | 'reabrir'
-- ---------------------------------------------------------------------
create or replace function public.tarea_resolver(
    p_id     bigint,
    p_accion text,
    p_nota   text     default null,
    p_dias   integer  default null
)
returns public.tareas
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_row     public.tareas;
    v_estatus text;
begin
    v_estatus := case p_accion
        when 'atender'  then 'atendida'
        when 'posponer' then 'pospuesta'
        when 'archivar' then 'archivada'
        when 'reabrir'  then 'pendiente'
        else null end;

    if v_estatus is null then
        raise exception 'Acción no válida: %  (usa atender | posponer | archivar | reabrir)', p_accion;
    end if;

    update public.tareas
    set estatus         = v_estatus,
        nota_resolucion  = coalesce(p_nota, nota_resolucion),
        posponer_hasta   = case when p_accion = 'posponer'
                                then now() + (coalesce(p_dias, 7) || ' days')::interval
                                else null end,
        resuelta_en      = case when v_estatus in ('atendida','archivada') then now() else null end,
        resuelta_por     = case when v_estatus <> 'pendiente' then auth.uid() else resuelta_por end,
        actualizada_en   = now()
    where id = p_id
    returning * into v_row;

    if not found then
        raise exception 'La tarea % no existe', p_id;
    end if;
    return v_row;
end $$;

grant execute on function public.tarea_resolver(bigint, text, text, integer) to authenticated;


-- ---------------------------------------------------------------------
-- 5. Vista de conveniencia: lo que la bandeja debe mostrar hoy
-- ---------------------------------------------------------------------
create or replace view public.v_tareas_pendientes as
select *
from public.tareas
where estatus = 'pendiente'
   or (estatus = 'pospuesta' and posponer_hasta is not null and posponer_hasta <= now());

grant select on public.v_tareas_pendientes to authenticated;


-- ---------------------------------------------------------------------
-- 6. Job diario de pg_cron (07:15 hora centro = 13:15 UTC)
--    Red de seguridad del trigger + reactiva las pospuestas vencidas.
-- ---------------------------------------------------------------------
do $$
begin
    if exists (select 1 from pg_extension where extname = 'pg_cron') then
        perform cron.schedule(
            'tareas_inventario_diario',
            '15 13 * * *',
            'select public.tareas_sync_inventario(null);'
        );
        raise notice 'Job pg_cron "tareas_inventario_diario" programado (13:15 UTC).';
    else
        raise notice 'pg_cron no instalado: se omite el job. El trigger y la app igual crean las tareas en tiempo real.';
    end if;
end $$;


-- ---------------------------------------------------------------------
-- 7. Backfill: crea las tareas de lo que HOY ya está bajo mínimo
-- ---------------------------------------------------------------------
select public.tareas_sync_inventario(null) as productos_evaluados;

commit;


-- =====================================================================
--  Consultas útiles (opcionales)
-- =====================================================================
-- select id, prioridad, titulo, estatus, posponer_hasta, creada_en
-- from public.tareas where estatus <> 'archivada' order by prioridad, creada_en;
--
-- select estatus, count(*) from public.tareas group by estatus;
--
-- -- historial de un producto:
-- select * from public.tareas
-- where entidad_tipo = 'producto' and entidad_id = :id order by creada_en desc;
